### ISSUE TITLE
pth files

### ISSUE THREAD

**Issue by stuaxo** [brbsix/virtualenv-mv#2]
Hi,
   This should probably check .pth files in site packages.    Usually the paths in these will be absolute paths pointing outside of the virtualenv, but there's no reason it couldn't include absolute paths pointing into the virtualenv too.

S

**Comment by brbsix** [comment]
c03d8bd8b5e3e2d4f3ee175bdd6c882b13daa1e3

Done, so long as they're absolute paths, each on their own line. I don't want to risk doing anything too involved.

Small world btw, I use vext all the time, so thanks for that!

**Comment by stuaxo** [comment]
Yes keeping it simple is sensible wrt path files :)

Glad you find vext useful, I'm curious which library you use it with ?

**Comment by brbsix** [comment]
Mostly PyQt5, but I've also used PyQt4 and gi. Installation sure is noisy (it looks like ruamel.yaml is largely responsible) but everything works as expected.

**Comment by stuaxo** [comment]
Cool, cheers for the feedback - I will bear the noise in mind.  Have to admit I only use it for GI, so quite surprising it works enough for PyQt4 + 5.    :)
